### ISSUE TITLE
移动端是否可以使用

### ISSUE THREAD

**Issue by zwq8299174** [Estelle00/vue-wow#12]
之前PC用了这个插件，现在在做一个移动端的项目，貌似动画有点BUG  想问下是否支持移动端的滚动动画，我在参数中没有看到移动端的相关参数

**Comment by Estelle00** [comment]
理论上是可以直接使用的因为但是没有测试 有什么问题你可以反馈下

**Comment by zwq8299174** [comment]
晚上下班之前测试了一下，移动端的动画触发不太正确，因为移动端滚动的时候有惯性，向上滑一下虽然手指没有继续滑屏幕但是页面还是会向下滚动，这时候如果需要触发动画的元素进入屏幕，是不会触发动画的，只有当屏幕停止了滚动，才会触发滚动事件，这个应该是移动端的特性，不过我看wowjs本身是支持移动端的而且不会出现我上面说的这种情况，我看了下你的源码，以为你里面整合了wowjs，只需要在你初始化wuwjs的地方加上支持移动端的参数就好了，看完源码发现你没有引用wowjs，自己写了滚动事件，那貌似需要单独的为移动端做一下支持了。

**Comment by Estelle00** [comment]
刚刚尝试修复了一波，你更新下试试

**Comment by zwq8299174** [comment]
嗯呢，更新了下貌似是可以了，还好你在一直优化，帮你推广了，哈哈
