### ISSUE TITLE
disable animations on mobile in Vue/Nuxt

### ISSUE THREAD

**Issue by gaisinskii** [Estelle00/vue-wow#14]
Hello!

I have a question regarding animations behavior on mobile devices in Vue.js/Nuxt.js. 
The question is: **How do i disable animations on mobile ?**

In nuxt.js i have a vue-wow.js file in plugins folder. In that file i register globally the vue-wow component like that:

```
import Vue from 'vue';
import VueWow from 'vue-wow';

// mount with global
Vue.use(VueWow);
```

Now i want to disable mobile animations, below that code i do:

```
export default ({ app }) => {
  app.VueWow = new VueWow({
    mobile: false,
  });
};
```

And that ^^^^ code disables animations not only on mobiles, but everywhere!

**Comment by Estelle00** [comment]
try it.
```vue
<template>
  <u-animate-container
    :config="config"
  >
    <u-animate
      name="fadeIn"
      delay="0s"
      duration="1s"
      :iteration="1"
      :offset="0"
      animateClass="animated"
      :begin="false" 
    >
      测试
    </u-animate>
  </u-animate-container>
</template>
<script>
  export default {
    data () {
      return {
        config: {
          mobile: false
        }
      }
    } 
  }
</script>
```

**Comment by gaisinskii** [comment]
@Estelle00  By first look seems that it works! Thank you! I will get in touch with you if something goes wrong.
One more time, thank you!
